### ISSUE TITLE
Error on run

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#103]
With the latest update I am getting the following error on starting the application and it exits. The 24-hour clock timestamp is working now though :)

2020/07/08 14:48:47 ERROR __main__.exception_handler Uncaught exception : Traceback (most recent call last):
  File "C:\Other programs\QualCoder-master\qualcoder\qualcoder.py", line 1008, in <module>
    gui()

  File "C:\Other programs\QualCoder-master\qualcoder\qualcoder.py", line 1001, in gui
    ex = MainWindow(qual_app)

  File "C:\Other programs\QualCoder-master\qualcoder\qualcoder.py", line 336, in __init__
    self.init_ui()

  File "C:\Other programs\QualCoder-master\qualcoder\qualcoder.py", line 345, in init_ui
    self.ui.actionOpen_Recent_Project.triggered.connect(self.open_recent_project)

AttributeError: 'Ui_MainWindow' object has no attribute 'actionOpen_Recent_Project'

**Comment by ccbogel** [comment]
Fixed. Apologies, one of the updated files I uploaded into the wrong folder.

**Comment by glocalglocal** [comment]
Another error. 

2020/07/08 23:16:45 ERROR __main__.exception_handler Uncaught exception : Traceback (most recent call last):
  File "C:\Other programs\QualCoder-master\qualcoder\qualcoder.py", line 1008, in <module>
    gui()

  File "C:\Other programs\QualCoder-master\qualcoder\qualcoder.py", line 1001, in gui
    ex = MainWindow(qual_app)

  File "C:\Other programs\QualCoder-master\qualcoder\qualcoder.py", line 336, in __init__
    self.init_ui()

  File "C:\Other programs\QualCoder-master\qualcoder\qualcoder.py", line 345, in init_ui
    self.ui.actionOpen_Recent_Project.triggered.connect(self.open_recent_project)

AttributeError: 'Ui_MainWindow' object has no attribute 'actionOpen_Recent_Project'

**Comment by ccbogel** [comment]
It should be correct. Right now, I downloaded the zip unpacked it and it ran fine.

**Comment by glocalglocal** [comment]
Working now. Not sure what happened there.
