### ISSUE TITLE
Manage Files error

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#173]
I simply selected Manage Files and got this:

ERROR manage_files.exception_handler Uncaught exception: Traceback (most recent call last):
  File "C:\Other programs\QualCoder-master\qualcoder\qualcoder.py", line 777, in manage_files
    ui = DialogManageFiles(self.app, self.ui.textEdit)

  File "C:\Other programs\QualCoder-master\qualcoder\manage_files.py", line 136, in __init__
    self.load_file_data()

  File "C:\Other programs\QualCoder-master\qualcoder\manage_files.py", line 260, in load_file_data
    self.check_attribute_placeholders()

  File "C:\Other programs\QualCoder-master\qualcoder\manage_files.py", line 220, in check_attribute_placeholders
    cur = self.app.conn.cursor()

AttributeError: 'NoneType' object has no attribute 'cursor'

**Comment by glocalglocal** [comment]
[thanks to markdown, github converted '__' to bold in my previous post]

And then I keep getting an error whatever I do:

```
ERROR code_text.exception_handler Uncaught exception:
Traceback (most recent call last):
  File "C:\Other programs\QualCoder-master\qualcoder\qualcoder.py", line 799, in text_coding
    ui = DialogCodeText(self.app, self.ui.textEdit, self.dialogList)

  File "C:\Other programs\QualCoder-master\qualcoder\code_text.py", line 110, in __init__
    self.filenames = self.app.get_text_filenames()

  File "C:\Other programs\QualCoder-master\qualcoder\qualcoder.py", line 204, in get_text_filenames
    cur = self.conn.cursor()

AttributeError: 'NoneType' object has no attribute 'cursor'
```

**Comment by ccbogel** [comment]
I am not sure what has caused this error. However, the error tells me that the program has lost the connection to the database.

**Comment by ccbogel** [comment]
A possible cause is if the path to the database has changed - e.g.the folder project folder was moved. I will leave this issue open for a couple of weeks. If it does not re-occur I will close it then.
