### ISSUE TITLE
Bug: Manage Attributes error

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#201]
Manage Attributes produces the following error:

ERROR attributes.exception_handler Uncaught exception:
Traceback (most recent call last):
  File "C:\Other programs\QualCoder-master\qualcoder\qualcoder.py", line 740, in manage_attributes
    ui = DialogManageAttributes(self.app, self.ui.textEdit)

  File "C:\Other programs\QualCoder-master\qualcoder\attributes.py", line 95, in __init__
    self.fill_tableWidget()

  File "C:\Other programs\QualCoder-master\qualcoder\attributes.py", line 249, in fill_tableWidget
    self.ui.label.setText(_("Attributes: ") + str(len(self.attributes)))

AttributeError: 'Ui_Dialog_manage_attributes' object has no attribute 'label'

**Comment by ccbogel** [comment]
fixed
