### ISSUE TITLE
Bug: Error on startup

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#226]
Just downloaded the latest version and got this error on startup: 

ERROR __main__.exception_handler Uncaught exception : Traceback (most recent call last):
  File "C:\Other programs\QualCoder-master\qualcoder\qualcoder.py", line 1385, in <module>
    gui()

  File "C:\Other programs\QualCoder-master\qualcoder\qualcoder.py", line 1378, in gui
    ex = MainWindow(qual_app)

  File "C:\Other programs\QualCoder-master\qualcoder\qualcoder.py", line 490, in __init__
    self.init_ui()

  File "C:\Other programs\QualCoder-master\qualcoder\qualcoder.py", line 559, in init_ui
    self.settings_report()

  File "C:\Other programs\QualCoder-master\qualcoder\qualcoder.py", line 700, in settings_report
    msg += _("Speaker name format") + ": " + self.app.settings['speakernameformat'] + "\n"

TypeError: can only concatenate str (not "int") to str

**Comment by ccbogel** [comment]
ok sorry, will look asap

**Comment by ccbogel** [comment]
ok try now

**Comment by glocalglocal** [comment]
No error but it automatically opened a recent project even though I had closed the project before the last time I exited qualcoder. It wasn't even the most recent one.

**Comment by ccbogel** [comment]
Yes I get this too. Maybe I should have QualCoder not open any project itself. and leave that for the user to do.

**Comment by glocalglocal** [comment]
It is quite nice starting qualcoder in the morning and diving into where you were last night, but I see what you mean.

**Comment by ccbogel** [comment]
its a bit quirky, in how it saves recent project then reopens them. So I will set it to not automatically open a project.
