### ISSUE TITLE
Bug: qualocoder won't start 

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#257]
I deleted recent_projects.txt to fix another issue as advised and qualcoder now won't start. The console output below. When I restore recent_projects.txt qualcoder runs again.  

'_io.TextIOWrapper' object has no attribute 'open'
Traceback (most recent call last):
  File "C:\Other programs\QualCoder-master\qualcoder\qualcoder.py", line 1568, in <module>
    gui()

  File "C:\Other programs\QualCoder-master\qualcoder\qualcoder.py", line 1532, in gui
    project_path = qual_app.get_most_recent_projectpath()

  File "C:\Other programs\QualCoder-master\qualcoder\qualcoder.py", line 233, in get_most_recent_projectpath
    result = self.read_previous_project_paths()

  File "C:\Other programs\QualCoder-master\qualcoder\qualcoder.py", line 155, in read_previous_project_paths
    logger.information('No previous projects found')

AttributeError: 'Logger' object has no attribute 'information'
Error in sys.excepthook:
Traceback (most recent call last):
  File "C:\Other programs\QualCoder-master\qualcoder\qualcoder.py", line 105, in exception_handler
    logger.error(_("Uncaught exception : ") + text)
NameError: name '_' is not defined

Original exception was:
Traceback (most recent call last):
  File "C:\Other programs\QualCoder-master\qualcoder\qualcoder.py", line 151, in read_previous_project_paths
    with open(self.persist_path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\MKlon/.qualcoder\\recent_projects.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Other programs\QualCoder-master\qualcoder\qualcoder.py", line 1568, in <module>
    gui()
  File "C:\Other programs\QualCoder-master\qualcoder\qualcoder.py", line 1532, in gui
    project_path = qual_app.get_most_recent_projectpath()
  File "C:\Other programs\QualCoder-master\qualcoder\qualcoder.py", line 233, in get_most_recent_projectpath
    result = self.read_previous_project_paths()
  File "C:\Other programs\QualCoder-master\qualcoder\qualcoder.py", line 155, in read_previous_project_paths
    logger.information('No previous projects found')
AttributeError: 'Logger' object has no attribute 'information'

**Comment by ccbogel** [comment]
Oh, perhaps for now create a blank file there in .qualcoder called recent_projects.txt

**Comment by glocalglocal** [comment]
It starts OK with the blank file and the file is populated with the date+recent files. Were the dates supposed to also appear on the Open Recent Project menu? If yes, they aren't.

**Comment by ccbogel** [comment]
The dates sre not to show.
