### ISSUE TITLE
Uncaught expression when trying to import files on a new project

### ISSUE THREAD

**Issue by WPFilmmaker** [ccbogel/QualCoder#319]
**Describe the bug**
After creating a new project managing files 

**To Reproduce**
Create new project
click on manage files and the error appears

**Expected behavior**
that i can manage files from the first use

**What fixes the issue**
Restarting Qualcoder fixes the issue

**Desktop (please complete the following information):**
Lubuntu 18.04 QualCoder 2.1 (it says 2.0 but it should be 2.1 I remember there was an issue displaying the wrong version number).

Traceback (most recent call last):
  File "/usr/share/qualcoder/qualcoder.py", line 924, in manage_files
    ui = DialogManageFiles(self.app, self.ui.textEdit)

  File "/usr/share/qualcoder/manage_files.py", line 147, in __init__
    self.load_file_data()

  File "/usr/share/qualcoder/manage_files.py", line 272, in load_file_data
    self.check_attribute_placeholders()

  File "/usr/share/qualcoder/manage_files.py", line 232, in check_attribute_placeholders
    cur = self.app.conn.cursor()

AttributeError: 'NoneType' object has no attribute 'cursor

**Comment by WPFilmmaker** [comment]
I have something similar (maybe) on windows 10: https://i.imgur.com/qhahwfC.png

My colleague terminal result:
<urlopen error [Errno 11001] getaddrinfo failed>
Writing to C:\Users\пс/.qualcoder\recent_projects.txt
Traceback (most recent call last):
  File "C:\qualcoder\manage_files.py", line 661, in view
    if self.source[x]['mediapath'] is not None and 'docs:' not in self.source[x]['mediapath']:

IndexError: list index out of range
PARSING ERROR:StartTag: invalid element name, line 1, column 253 (<string>, line 1)
PARSING ERROR:StartTag: invalid element name, line 1, column 253 (<string>, line 1)
Traceback (most recent call last):
  File "C:\qualcoder\qualcoder.py", line 1020, in text_coding
    files = self.app.get_text_filenames()

  File "C:\qualcoder\qualcoder.py", line 276, in get_text_filenames
    cur = self.conn.cursor()

AttributeError: 'NoneType' object has no attribute 'cursor'
Traceback (most recent call last):
  File "C:\qualcoder\qualcoder.py", line 1122, in REFI_codebook_import
    Refi_import(self.app, self.ui.textEdit, "qdc")

  File "C:\qualcoder\refi.py", line 108, in __init__
    self.import_codebook()

  File "C:\qualcoder\refi.py", line 136, in import_codebook
    counter += self.sub_codes(cb, None)

  File "C:\qualcoder\refi.py", line 213, in sub_codes
    counter += self.sub_codes(e, last_insert_id)

  File "C:\qualcoder\refi.py", line 179, in sub_codes
    cur = self.app.conn.cursor()

AttributeError: 'NoneType' object has no attribute 'cursor'
Traceback (most recent call last):
  File "C:\qualcoder\qualcoder.py", line 1020, in text_coding
    files = self.app.get_text_filenames()

  File "C:\qualcoder\qualcoder.py", line 276, in get_text_filenames
    cur = self.conn.cursor()

AttributeError: 'NoneType' object has no attribute 'cursor'
Traceback (most recent call last):
  File "C:\qualcoder\qualcoder.py", line 1020, in text_coding
    files = self.app.get_text_filenames()

  File "C:\qualcoder\qualcoder.py", line 276, in get_text_filenames
    cur = self.conn.cursor()

AttributeError: 'NoneType' object has no attribute 'cursor'
Traceback (most recent call last):
  File "C:\qualcoder\qualcoder.py", line 1020, in text_coding
    files = self.app.get_text_filenames()

  File "C:\qualcoder\qualcoder.py", line 276, in get_text_filenames
    cur = self.conn.cursor()

AttributeError: 'NoneType' object has no attribute 'cursor'
Traceback (most recent call last):
  File "C:\qualcoder\qualcoder.py", line 1020, in text_coding
    files = self.app.get_text_filenames()

  File "C:\qualcoder\qualcoder.py", line 276, in get_text_filenames
    cur = self.conn.cursor()

AttributeError: 'NoneType' object has no attribute 'cursor'
Traceback (most recent call last):
  File "C:\qualcoder\qualcoder.py", line 1020, in text_coding
    files = self.app.get_text_filenames()

  File "C:\qualcoder\qualcoder.py", line 276, in get_text_filenames
    cur = self.conn.cursor()

AttributeError: 'NoneType' object has no attribute 'cursor'
Traceback (most recent call last):
  File "C:\qualcoder\qualcoder.py", line 1020, in text_coding
    files = self.app.get_text_filenames()

  File "C:\qualcoder\qualcoder.py", line 276, in get_text_filenames
    cur = self.conn.cursor()

AttributeError: 'NoneType' object has no attribute 'cursor'
Traceback (most recent call last):
  File "C:\qualcoder\qualcoder.py", line 1020, in text_coding
    files = self.app.get_text_filenames()

  File "C:\qualcoder\qualcoder.py", line 276, in get_text_filenames
    cur = self.conn.cursor()

AttributeError: 'NoneType' object has no attribute 'cursor'

**Comment by ccbogel** [comment]
hmm, I think I will put out a new release soon.
This error does not occur from the latest github code.

**Comment by ccbogel** [comment]
@WPFilmmaker The error does tell me that the connection to the database was lost. This could be from that initial error:

IndexError: list index out of range
PARSING ERROR:StartTag: invalid element name, line 1, column 253 (, line 1)
PARSING ERROR:StartTag: invalid element name, line 1, column 253 (, line 1)

I have added extra code to prevent this error.
