### ISSUE TITLE
Window 10 error

### ISSUE THREAD

**Issue by ccbogel** [ccbogel/QualCoder#33]
In WIndows 10 qualcoder will not run now (for me) due to a module needed for the vlc bindings (for video and audio).  Needs libvlc.dll  so need to add a path for this
One easy solution is to not have audio and video on windows, so might need to have an exception to avoid loading audio/video related modules.

P:\>python S:\Colin_Curtain\QualCoder-master\QualCoder-master\qualcoder\qualcoder.py
Traceback (most recent call last):
  File "S:\Colin_Curtain\QualCoder-master\QualCoder-master\qualcoder\vlc.py", line 210, in <module>
    dll, plugin_path  = find_lib()
  File "S:\Colin_Curtain\QualCoder-master\QualCoder-master\qualcoder\vlc.py", line 170, in find_lib
    dll = ctypes.CDLL(libname)
  File "C:\Users\ccurtain\AppData\Local\Programs\Python\Python37-32\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

**Comment by ccbogel** [comment]
SOme suggestions here: https://stackoverflow.com/questions/42045887/python-vlc-install-problems

**Comment by ccbogel** [comment]
One potential cause is the version of python installed might be 32 bits but the installed vlc is 64 bits (or vice versa). 
Potential solution is that you might need to install the other version of vlc for it to work with QualCoder on Windows.
