### ISSUE TITLE
Application won't open

### ISSUE THREAD

**Issue by srogstad** [ccbogel/QualCoder#427]
Hello,
I recently installed this software, but it just won't open on my computer at all. Here is the error report I'm getting.
![Screenshot from 2021-04-22 17-08-00](https://user-images.githubusercontent.com/6274012/115785503-8ad71600-a38d-11eb-874d-56cbdc8f81f9.png)
![Screenshot from 2021-04-22 17-08-21](https://user-images.githubusercontent.com/6274012/115785506-8b6fac80-a38d-11eb-9729-d53c9b5f0aab.png)

**Comment by ccbogel** [comment]
Hmm, this was from the Debian install, I am guessing.
I am not sure how to fix this at the moment.
Can you try downloading the latest code: https://github.com/ccbogel/QualCoder  using the Green Code button.
Then unzip the folder in Downloads, then open the terminal and type:
python3 Downloads/QualCoder-master/qualcoder/qualcoder.py 

and tell me if it works

**Comment by srogstad** [comment]
I just tried it and got this error. Perhaps I need to install additional python packages?

~/Downloads/QualCoder-master/qualcoder$ python3 qualcoder.py 
Traceback (most recent call last):
  File "qualcoder.py", line 45, in <module>
    from PyQt5 import QtCore, QtGui, QtWidgets
ModuleNotFoundError: No module named 'PyQt5'

**Comment by ccbogel** [comment]
Yes you need to install all these packages, as it mentions in the readme:
python3-lxml python3-ply python3-six python3-chardet python3-qt5 python3-pillow
I think for Suse: 
sudo zypper refresh && sudo zypper update
sudo zypper install python3-lxml python3-ply python3-six python3-chardet python3-qt5 python3-pillow

**Comment by srogstad** [comment]
I had done that and gotten an error about qt5 not being found:
sudo apt install python3-lxml python3-ply python3-six python3-chardet python3-qt5 python3-pillow
[sudo] password for : 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'python3-pil' instead of 'python3-pillow'
E: Unable to locate package python3-qt5

So I had tried this: sudo apt-get install python3-pyqt5
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-pyqt5 is already the newest version (5.10.1+dfsg-1ubuntu2)

And PyQt5 seems to be installed but I still got that error about it not finding PyQt5. Maybe I'm still missing something or a path isn't set right somewhere. I'll keep working on it, I definitely want to try QualCoder.

**Comment by ccbogel** [comment]
ok. It might be because multiple versions of python are installed.
Try this approach:
Download the latest code using the green Code button (not in the releases). Unzip it to the Download directory
Then try the following in the Terminal:
First:
python3 Downloads/Qualcoder-master/qualcoder/qualcoder.py

if this fails just run python3 and tell me what version
Ctrl + Z to exit python

if the version is 3.7  (for example)
then try:
python3.7 Downloads/Qualcoder-master/qualcoder/qualcoder.py

**Comment by srogstad** [comment]
Sorry for the delay. It still gives the same error:

~/Downloads/QualCoder-master/qualcoder$ python3 qualcoder.py 
Traceback (most recent call last):
  File "qualcoder.py", line 45, in <module>
    from PyQt5 import QtCore, QtGui, QtWidgets
ModuleNotFoundError: No module named 'PyQt5'
~/Downloads/QualCoder-master/qualcoder$ python3
Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
~/Downloads/QualCoder-master/qualcoder$ python3.8 qualcoder.py 
Traceback (most recent call last):
  File "qualcoder.py", line 45, in <module>
    from PyQt5 import QtCore, QtGui, QtWidgets
ModuleNotFoundError: No module named 'PyQt5'
~/Downloads/QualCoder-master/qualcoder$ python3.8.5 qualcoder.py 
python3.8.5: command not found

**Comment by ccbogel** [comment]
Making progress :)  your post helped.
From the Terminal run this:
python3 -m pip install pyqt5

This should install the pyqt5 for the version of python

**Comment by ccbogel** [comment]
Hi, yes those errors are ok. the log error will disappear as now a log file will be created.
I'm glad its working for you.
