### ISSUE TITLE
Uncaught Exception when trying to export csv

### ISSUE THREAD

**Issue by KneckerMcKnack** [ccbogel/QualCoder#585]
When trying to export a coding report as .csv, an uncaught exception error occurs:

Steps:
Selected Reports > Coding Reports
Selected one Coder
Selected one File
Selected all Codes
Pressed the run button
Selected csv from export drop down list

Result:
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/Qualcoder-2.9-py3.9.egg/qualcoder/report_codes.py", line 501, in export_option_selected
    self.export_csv_file()

  File "/usr/lib/python3.9/site-packages/Qualcoder-2.9-py3.9.egg/qualcoder/report_codes.py", line 556, in export_csv_file
    if self.text_results == [] and self.image_results == [] and self.av_results == []:

AttributeError: 'DialogReportCodes' object has no attribute 'text_results'
```

All other exports work fine.

System:
 - Arch / Manjaro / KDE
 - Qualcoder latest

Greetings :)

**Comment by ccbogel** [comment]
thanks resolved now
