### ISSUE TITLE
Uncaught Exception

### ISSUE THREAD

**Issue by irakuri** [ccbogel/QualCoder#592]
When I'm trying to run "Code text" Alt+T, it's show me this message.
Any suggestion?

`
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/Qualcoder-2.9-py3.8.egg/qualcoder/__main__.py", line 1142, in text_coding
    ui = DialogCodeText(self.app, self.ui.textEdit, self.ui.tab_reports)

  File "/usr/local/lib/python3.8/dist-packages/Qualcoder-2.9-py3.8.egg/qualcoder/code_text.py", line 183, in __init__
    self.ui.textEdit.customContextMenuRequested.connect(self.textedit_menu)

AttributeError: 'DialogCodeText' object has no attribute 'textedit_menu'
`
OS: Ubuntu 20.04

**Comment by ccbogel** [comment]
@irakuri Thank you. I made a mistake with variable names yesterday.
Now fixed.
Please download again and try again.
with regards Colin
