### ISSUE TITLE
TypeError: can only concatenate str (not "bytes") to str

### ISSUE THREAD

**Issue by ricardoamaro** [ccbogel/QualCoder#623]
**Describe the bug**
Issue 1:
Application throws `TypeError: can only concatenate str` while doing autocoding.

Issue 2 (filed a feature request https://github.com/ccbogel/QualCoder/issues/625):
An imported text sometimes generates special characters. Those characters are not escaped or cleaned up during import and could break the autocoding with line endings.

**To Reproduce**
Steps to reproduce the behavior of Issue 1:

Do autocoding of sentences with line endings.

![image](https://user-images.githubusercontent.com/384962/159161238-ee144849-48ec-491e-8669-6d63da17b307.png)

![image](https://user-images.githubusercontent.com/384962/159162324-9d398b85-d9d0-4243-8311-d83c57d3b443.png)

```
$ qualcoder 
Traceback (most recent call last):
  File "/home/ricardo/.pyenv/versions/3.7.9/lib/python3.7/site-packages/qualcoder/code_text.py", line 2997, in button_autocode_sentences_this_file
    self.code_sentences("")

  File "/home/ricardo/.pyenv/versions/3.7.9/lib/python3.7/site-packages/qualcoder/code_text.py", line 3201, in code_sentences
    "\nUsing line ending: ") + ending + "\n" + msg)

TypeError: can only concatenate str (not "bytes") to str
```

I also believe these characters should be cleaned up:

![image](https://user-images.githubusercontent.com/384962/159162521-ae52c842-b81a-424d-8ab2-253e76c99aee.png)

```
    e picture they paint is compelling. ey describe how eﬀective IT
```

**Expected behavior**
The code_text.py, line 3201, in code_sentences should not break.

**Screenshots**
Already above.

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu
 - Version 21.10

**Comment by ricardoamaro** [comment]
I did some debug around line 3201 and I see that "text" shows this: 

```
ipdb> text
b'iVBORw0KGgoAAAANSUhEUgAAAFAAAABCCAIAAABPbcZqAAAWD3pUWHRSYXcgcHJvZmlsZSB0eXBlIGV4aWYAAHjarZtnUmQ7kIX/axWzBHmzHNmI2cEsf76Ubjko6NcNEE3BNUqlO3lSUqv5f/+71P/wlZKOyoeUY4lR8+WLL7byS9bn63wa7ffP/RWuW/z9cl15e92wXHJ8uvNnnNfzlevh8ULy1/X2el2lfo2Tr4GuG7cBnUgWYddz+RrI2XPdXH+rcr1X/ZM617/V7b4d2rn18W+fMMYIjOesstMZp/mZRYo7/yr/HD+NKzxkXOJ3x2flrnlvO3X/9YPxhntvO12vJ9yrKZSO1wPxg42u6ya8t9220POMzO1X+3pDezP089ez7dbIa82jXfURS0V1KaWvIfZvPIg5vduvRb4JOFyd+ZTvwndGxY7HBt5sfHdlirFYexlmYKpZZu7PbjpT9HbaxKe1HSvLteySLbY7cYGXb7NscsUN5TKe6HjNcdne52K23LLldZORPAxPWsNghjc+fat3F//l+z7QWhK6xogxh9u24qeVmGYa4jn5yVM4xKzLpmHbd3+ru5ceX+JYhwfDNnNGwarbGaIF84gtt/3seC5or/RJDZPGNYA4HllMxjg8oKNxwUSjk7XJGOyY8U9l5tZ52/CACcEOoxa+cS7inGxFNu8ks5+1wZ7LQAuOCC6SKhkPVZzlfSB+ks/EUA0ueBVCiCGFHEqo0UUfQ4wxRcGomlzyKaSYUsqppJpd9jnkmFPOueRabHFAWCixJFVyKaVWhFaGrrxdeaLWZptrvoUWW2q5lVY74dN9Dz321HMvvQ473CD9RxxJjTzKqNNMQmn6GWacaeZZZl3E2nLLr7DiSiuvsurda5dXX71mPnjue6+Zy2viMb+fSw+vcRkAv4YwAidBfIbHrDd4PIkHCGgrPtPZeG/Fc+IzXSxJESxeM0GcM4x....
```

**Comment by ricardoamaro** [comment]
Not sure is decoding it could fix the issue meanwhile, but I'll create a PR

```
ipdb> test = _("\nsome string: ") + text
*** TypeError: can only concatenate str (not "bytes") to str
ipdb> test = _("\nsome string: ") + text.decode("utf-8")
ipdb> test
'\nsome string: iVBORw0KGgoAAAANSUhEUgAAAFAAAABCCAIAAABPbcZqAAAWD3pUWHRSYXcgcHJvZmls
```
