### ISSUE TITLE
QualCoder on Python3.11

### ISSUE THREAD

**Issue by hleplaa** [ccbogel/QualCoder#730]
**Describe the bug**
I tried to install QualCoder on Python 3.11, but kept getting error messages (about not being able to produce the wheel, as well as about lxml).

**To Reproduce**
Follow the manual closely in Python 3.11 (windows computer).

**Expected behavior**
The manual worked eventually perfectly fine when I switched to Python 3.7 (the version used when the manual was written?).
We did not try Python 3.8, 3.9, or 3.10.

**Comment by ccbogel** [comment]
Yes, there is an issue with the lxml module in 3.11 on Windows.  I will look for a solution.

**Comment by ccbogel** [comment]
There is a bug report for the lxml module:
https://bugs.launchpad.net/lxml/+bug/1969912

So far I have found another python module that I am testing to do the same job:
https://docs.python.org/3/library/xml.etree.elementtree.html

**Comment by ccbogel** [comment]
REFI codebook and project import now will work without the lxml module. 
TODO: Still have to fix the docx import module.

**Comment by ccbogel** [comment]
@hleplaa Please test it out. The lxml will still produce errors when you try to install it via the manual commands for python 3.11. But not having lxml installed will not stop you from running the QualCoder program, now.

**Comment by hleplaa** [comment]
I will do that tomorrow, I'll keep you posted.

**Comment by hleplaa** [comment]
I can't seem to figure it out currently. I keep running into problems with QtCore:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Program Files\QualCoder-master\qualcoder\__main__.py", line 47, in <module>
    from PyQt6 import QtCore, QtGui, QtWidgets
ImportError: DLL load failed while importing QtCore: The specified module could not be found.

I've tried it now with both Python3.11 as well as with Python 3.7: the same error message appears. I will ask a more tech-savvy colleague to help me out on Wednesday to get QualCoder running again: the error may very well be on my part.

**Comment by ccbogel** [comment]
Did you install pyqt6 (and the other modules) for the exact version of python you are running?
e.g. 
py -3.10 -m pip install wheel pyqt6 chardet ebooklib lxml openpyxl Pillow ply pdfminer.six pandas plotly pydub python-vlc rispy SpeechRecognition

py -3.7 -m pip install wheel pyqt6 chardet ebooklib lxml openpyxl Pillow ply pdfminer.six pandas plotly pydub python-vlc rispy SpeechRecognition

py -3.11 -m pip install wheel pyqt6 chardet ebooklib lxml openpyxl Pillow ply pdfminer.six pandas plotly pydub python-vlc rispy SpeechRecognition

One more thing:
Instead of doing a manual install on Windows 10 or 11, why not use the packed up exe for Qualcoder on the 3.1 release page?
The exe contains a python 3.10 version and all the relevant modules inside it.
Download it, double-click to run, and say yes (if asked) to allow to run, as Windows does not know the publisher. 

https://github.com/ccbogel/QualCoder/releases

**Comment by hleplaa** [comment]
>Instead of doing a manual install on Windows 10 or 11, why not use the packed up exe for Qualcoder on the 3.1 release page? (ah - or was that because you have problems with VLC? - i cant remember).
This was a fantastic suggestion: within 2 minutes it was running again. 

I do think I installed pyqt6 for an incorrect version; the specified commands seem familiair from when a colleague initially helped me out. That probably would have solved it.

Thank you for your time and help. The packed up exe is a fantastic solution for the "less-tech-savvy" such as myself.
