### ISSUE TITLE
Import of NVivo REFI-QDA file stalls

### ISSUE THREAD

**Issue by donnekgit** [ccbogel/QualCoder#743]
**Describe the bug**
When importing a qdpx project file exported from NVivo 12, the import stops at 6% with the following message:
```
Traceback (most recent call last):
  File "/home/kevin/data/Lois/QualCoder/qualcoder/lib/python3.10/site-packages/qualcoder/__main__.py", line 1375, in refi_project_import
    RefiImport(self.app, self.ui.textEdit, "qdpx")

  File "/home/kevin/data/Lois/QualCoder/qualcoder/lib/python3.10/site-packages/qualcoder/refi.py", line 148, in __init__
    self.import_project()

  File "/home/kevin/data/Lois/QualCoder/qualcoder/lib/python3.10/site-packages/qualcoder/refi.py", line 390, in import_project
    count = self.parse_notes(c)

  File "/home/kevin/data/Lois/QualCoder/qualcoder/lib/python3.10/site-packages/qualcoder/refi.py", line 1561, in parse_notes
    cur.execute("insert into journal(name,jentry,owner,date) values(?,?,?,?)",

IntegrityError: UNIQUE constraint failed: journal.name
```

OS: Ubuntu 22.04.
QC: 3.2.

I know this is probably the fault of the NVivo export, but is there any way around this?

**Comment by ccbogel** [comment]
Hmm, that's interesting. So in Nvivo can you have more than one journal using the same journal name?

**Comment by ccbogel** [comment]
OK. I think I have solved this problem. 
Instead of crashing, it will add random numbers to the duplicated journal name and should continue to import.
Please download the current code and test this with your Nvivo qdpx project file and let me know if it is successful, so that I can close this issue.

**Comment by donnekgit** [comment]
Gosh, I was trying to find out what NVivo journals were (my colleague has never used them either), and you've already fixed it! Sterling!
The qdpx file imports fine now;
```
Project XML parsing successful: True
Parse users. Loaded: 1
Parse codes and categories. Loaded: 401
Parsing and loading project memo
Parsed cases for file variables. Loaded: 0
Parsing sources. Loaded: 4
Duplicate journal name: 
Duplicate journal renamed to: _213
Duplicate journal name: 
Duplicate journal renamed to: _746
Duplicate journal name: 
Duplicate journal renamed to: _259
Duplicate journal name: 
Duplicate journal renamed to: _319
Duplicate journal name: 
Duplicate journal renamed to: _054
Duplicate journal name: 
Duplicate journal renamed to: _900
Duplicate journal name: 
Duplicate journal renamed to: _425
Duplicate journal name: 
Duplicate journal renamed to: _811
Duplicate journal name: 
Duplicate journal renamed to: _180
Duplicate journal name: 
Duplicate journal renamed to: _862
Duplicate journal name: 
Duplicate journal renamed to: _995
Duplicate journal name: 
Duplicate journal renamed to: _951
Duplicate journal name: 
Duplicate journal renamed to: _316
Duplicate journal name: 
Duplicate journal renamed to: _572
Duplicate journal name: 
Duplicate journal renamed to: _628
Duplicate journal name: 
Duplicate journal renamed to: _774
Duplicate journal name: 
Duplicate journal renamed to: _704
Duplicate journal name: 
Duplicate journal renamed to: _924
Duplicate journal name: 
Duplicate journal renamed to: _989
Duplicate journal name: 
Duplicate journal renamed to: _254
Duplicate journal name: 
Duplicate journal renamed to: _033
Duplicate journal name: 
Duplicate journal renamed to: _312
Duplicate journal name: 
Duplicate journal renamed to: _473
Duplicate journal name: 
Duplicate journal renamed to: _367
Duplicate journal name: 
Duplicate journal renamed to: _204
Parsing Notes. Journals loaded: 26
Parsing Notes. Text annotations loaded: 0
```
Not sure where all the journals come from, but they are all handled fine.
Thank you so much for sorting this out.

**Comment by ccbogel** [comment]
@donnekgit Before I close this issue. Can you open those journal entries and let me know what they might relate to. As QualCoder might be interpreting the Notes XML incorrectly. In Notes XML there are usually journal text entries and Text annotations.

**Comment by donnekgit** [comment]
I've checked these, and they seem to be annotations.

**Comment by ccbogel** [comment]
Hmm. Ok. So there needs to be a better solution. I am not sure I can do this without seeing the nvivo export file that caused the issue,  But i will try.

**Comment by donnekgit** [comment]
I've done a little test file which shows the same behaviour.  Can I send it to you somehow?

**Comment by donnekgit** [comment]
OK.  Attached.  I changed .qdpx to .zip.

[startrek.zip](https://github.com/ccbogel/QualCoder/files/10366726/startrek.zip)

**Comment by ccbogel** [comment]
Great, thank you.
