### ISSUE TITLE
Uncaugt Exceptions in 3.5 on Fedora 39 fresh install in 'Manage files'

### ISSUE THREAD

**Issue by pmwisse** [ccbogel/QualCoder#900]
**Describe the bug :**
Python outputs a list of exceptions when opening 'Manage files' (in which there are two audio files):

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/Qualcoder-3.4-py3.12.egg/qualcoder/__main__.py", line 1380, in manage_files
    ui = DialogManageFiles(self.app, self.ui.textEdit, self.ui.tab_coding, self.ui.tab_reports)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/Qualcoder-3.4-py3.12.egg/qualcoder/manage_files.py", line 195, in __init__
    self.load_file_data()

  File "/usr/local/lib/python3.12/site-packages/Qualcoder-3.4-py3.12.egg/qualcoder/manage_files.py", line 849, in load_file_data
    icon, metadata = self.get_icon_and_metadata(row[1])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/Qualcoder-3.4-py3.12.egg/qualcoder/manage_files.py", line 976, in get_icon_and_metadata
    instance = vlc.Instance()
               ^^^^^^^^^^^^^^

  File "/home/maarten/.local/lib/python3.12/site-packages/vlc.py", line 1838, in __new__
    return libvlc_new(len(args), args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/maarten/.local/lib/python3.12/site-packages/vlc.py", line 5014, in libvlc_new
    _Cfunction('libvlc_new', ((1,), (1,),), class_result(Instance),

  File "/home/maarten/.local/lib/python3.12/site-packages/vlc.py", line 302, in _Cfunction
    raise NameError('no function %r' % (name,))

NameError: no function 'libvlc_new'

**To Reproduce :**
As mentioned: install on Fedora 39 with the script that is intended for it. Then, QualCoder does not start by the way but there is a fix for that mentioned in one of the bug reports on GitHub, namely by reinstalling PyQT and after that, rerunning the script for Fedora. After that, Qualcoder starts, but after I imported two files, the 'Manage files' does not work anymore.

**Desktop (please complete the following information):**
 - OS: Fedora Linux, with kernel 6.8.4
 - Version 39 with all updates applied

**Comment by ccbogel** [comment]
Ah thanks, yes I forgot to update the version number in line 44 in the setup.py file from 3.4 to 3.5.

**Comment by ccbogel** [comment]
@pmwisse I tried looking for a solution to the python vlc module not working and am unable to resolve this. 

So, for audio/video (loading files or coding) either use a different OS or another qualitative software, is for now the only advice  I can offer.
I can add in some code that catches the error, but does not fix it.

**Comment by pmwisse** [comment]
Unfortunate but thanks for the reply!
