### ISSUE TITLE
Error while installing dependencies

### ISSUE THREAD

**Issue by bachnou3i** [ccbogel/QualCoder#903]
**Description:** 
I am trying to install QualCoder on ChromeOS. Everything went well apart from satisfying the pyqt6 dependency. I tried with Python 3.11 and 3.10 but same problem. 

**Steps to Reproduce:**
```
source qualcoder/bin/activate
pip install pyqt6
```
**Expected Behavior:**
install pyqt6 package

**Actual Behavior:**
```

Collecting pyqt6
  Using cached PyQt6-6.6.1.tar.gz (1.0 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [26 lines of output]
      pyproject.toml: line 7: using '[tool.sip.metadata]' to specify the project metadata is deprecated and will be removed in SIP v7.0.0, use '[project]' instead
      Traceback (most recent call last):
        File "/home/bachnou3i/QualCoder-3.5/qualcoder/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/bachnou3i/QualCoder-3.5/qualcoder/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/bachnou3i/QualCoder-3.5/qualcoder/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-r8oyk7c_/overlay/lib/python3.11/site-packages/sipbuild/api.py", line 46, in build_wheel
          project = AbstractProject.bootstrap('wheel',
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-r8oyk7c_/overlay/lib/python3.11/site-packages/sipbuild/abstract_project.py", line 92, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "/tmp/pip-build-env-r8oyk7c_/overlay/lib/python3.11/site-packages/sipbuild/project.py", line 587, in setup
          self.apply_user_defaults(tool)
        File "/tmp/pip-install-sn29tz46/pyqt6_6dcf604ebc3a4e8291401beed846b34c/project.py", line 66, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/tmp/pip-build-env-r8oyk7c_/overlay/lib/python3.11/site-packages/pyqtbuild/project.py", line 51, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/tmp/pip-build-env-r8oyk7c_/overlay/lib/python3.11/site-packages/sipbuild/project.py", line 237, in apply_user_defaults
          self.builder.apply_user_defaults(tool)
        File "/tmp/pip-build-env-r8oyk7c_/overlay/lib/python3.11/site-packages/pyqtbuild/builder.py", line 50, in apply_user_defaults
          raise PyProjectOptionException('qmake',
      sipbuild.pyproject.PyProjectOptionException
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
**Environment:**
**Operating System:** ChromeOS| Debian GNU/Linux 12 (bookworm)
**Bash version:** GNU bash, version 5.2.15(1)-release (aarch64-unknown-linux-gnu)
**Python version:** 3.10.14 (main, Mar 21 2024, 16:18:23) [GCC 11.2.0] on linux

![image](https://github.com/ccbogel/QualCoder/assets/9042895/803cbfa1-6ee2-4266-818a-09c7b893ddaf)

**Comment by ccbogel** [comment]
OK. Try using capitals for pyqt6:

pip install PyQt6`

**Comment by bachnou3i** [comment]
Same error

**Comment by kaixxx** [comment]
This seems to be a common issue with PyQt6 on ChromeOS, nothing specific to QualCoder. See for instance: https://stackoverflow.com/questions/73010472/require-help-installing-pyqt6
Try searching a little more if somebody found a solution installing PyQt6 an ChromeOS. Or ask for help in the PyQt community.
