### ISSUE TITLE
current code doesn't install on os x

### ISSUE THREAD

**Issue by bozo32** [ccbogel/QualCoder#983]
**Describe the bug :**
created a conda environment with python 3.12
activated that environment
git clone repository
pip install -r requirements.txt just fine
xtools is installed and functioning
pip install .
gets 
Successfully installed Qualcoder-3.6
on python __main__.py

(qualcoder) peter@peter qualcoder % python __main__.py 
Error in sys.excepthook:
Traceback (most recent call last):
  File "/Users/peter/miniconda3/envs/qualcoder/lib/python3.12/site-packages/qualcoder/error_dlg.py", line 94, in exception_hook
    logger.error(_("Uncaught exception: ") + msg + '\n' + tb)
                 ^
NameError: name '_' is not defined

Original exception was:
Traceback (most recent call last):
  File "/Users/peter/ai-stuff/QualCoder/qualcoder/__main__.py", line 49, in <module>
    from qualcoder.code_text import DialogCodeText
  File "/Users/peter/miniconda3/envs/qualcoder/lib/python3.12/site-packages/qualcoder/code_text.py", line 52, in <module>
    from .ai_search_dialog import DialogAiSearch
  File "/Users/peter/miniconda3/envs/qualcoder/lib/python3.12/site-packages/qualcoder/ai_search_dialog.py", line 29, in <module>
    from .ai_prompts import PromptsList, DialogAiEditPrompts
  File "/Users/peter/miniconda3/envs/qualcoder/lib/python3.12/site-packages/qualcoder/ai_prompts.py", line 341, in <module>
    _('These prompts are used in the AI search. They instruct the AI on how to decide \n'
    ^
NameError: name '_' is not defined
(qualcoder) peter@peter qualcoder % 

Removing the preceding _ s
in the 
prompts.py
file fixed it...but I think you might have those there to support translation/localisation?

-Peter

**Comment by ccbogel** [comment]
Yes, My error, I thought they needed _() translation methods, so changed it yesterday, but there is another reason for this. regards Colin. Have reverted it now.

**Comment by kaixxx** [comment]
I've also removed _() from prompt_scope_descriptions, which caused the same error: https://github.com/ccbogel/QualCoder/commit/bc6a5be9259b7b33b3e7abbd54e7df09eda1e39c

However, the general intention was right: These descriptions need translation. The problem is that at the time the descriptions are defined in ai_prompts.py, the translation function _() is not yet available, which causes an error. But I don't really understand where the function _() is defined, so it's hard for me to suggest a proper fix.
